baseURL = "https://sul.im/"
copyright = "Alexander Sulim"
googleAnalytics = "UA-391915-19"
languageCode = "en-US"
title = "Alexander Sulim"
theme = "hyde"
enableEmoji = true

[params]
  layoutReverse = true

[[menu.main]]
name = "Blog"
url = "/blog"

[[menu.main]]
name = "Now"
url = "/now"
