baseURL = "https://sul.im/"
copyright = "Alexander Sulim"
languageCode = "en-US"
title = "Alexander Sulim"
theme = "pure"
enableEmoji = true
ignoreErrors = ["error-remote-getjson"]     # Ignore error in offline mode

[sitemap]
priority = 0.5

[params]
  twitter = "soulim"

[menus]
  [[menus.main]]
    title = "Blog"
    name = "Blog"
    pageRef = "/blog"
    weight = 10
  [[menus.main]]
    title = "TIL"
    name = "TIL"
    pageRef = "/til"
    weight = 20
  [[menus.main]]
    title = "Now"
    name = "Now"
    pageRef = "/now"
    weight = 30
  [[menus.main]]
    title = "RSS"
    name = "RSS"
    pageRef = "/blog/index.xml"
    weight = 40

[privacy]
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
    disableInlineCSS = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[server]
  [[server.headers]]
    for = "/*"
    [server.headers.values]
      X-Frame-Options = "DENY"
      Content-Security-Policy = """\
                                default-src 'none'; \
                                base-uri 'self'; \
                                form-action 'self'; \
                                connect-src 'self'; \
                                font-src 'self'; \
                                frame-src 'self' https://www.youtube-nocookie.com; \
                                img-src 'self' data:; \
                                manifest-src 'self'; \
                                media-src 'self'; \
                                object-src 'none'; \
                                script-src 'self'; \
                                style-src 'self' 'unsafe-inline'; \
                                frame-ancestors 'none'\
                                """

