baseURL = "https://sul.im/"
copyright = "Alexander Sulim"
languageCode = "en-US"
title = "Alexander Sulim"
theme = "pure"
enableEmoji = true

[[menu.main]]
identifier = "blog"
title = "Blog"
name = "Blog"
url = "/blog/"

[[menu.main]]
identifier = "now"
title = "Now"
name = "Now"
url = "/now/"
