baseURL = "https://sul.im/"
copyright = "Alexander Sulim"
languageCode = "en-US"
title = "Alexander Sulim"
theme = "pure"
enableEmoji = true
ignoreErrors = ["error-remote-getjson"]     # Ignore error in offline mode

[sitemap]
priority = 0.5

[social]
  twitter = "soulim"

[[menu.main]]
identifier = "blog"
title = "Blog"
name = "Blog"
url = "/blog/"

[[menu.main]]
identifier = "now"
title = "Now"
name = "Now"
url = "/now/"

[privacy]
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
    disableInlineCSS = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[server]
  [[server.headers]]
    for = "/*"
    [server.headers.values]
      X-Frame-Options = "DENY"
      Content-Security-Policy = """\
                                default-src 'none'; \
                                connect-src 'self' https://plausible.io; \
                                font-src 'self'; \
                                frame-src 'self' https://www.youtube-nocookie.com; \
                                img-src 'self'; \
                                manifest-src 'self'; \
                                media-src 'self'; \
                                object-src 'none'; \
                                script-src 'self' https://plausible.io; \
                                style-src 'self' 'unsafe-inline'; \
                                frame-ancestors 'none'\
                                """

