on:
  push:
    branches:
    - master
name: Push workflow
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy website
        run: make deploy NETLIFY_ACCESS_TOKEN=${{ secrets.NETLIFY_ACCESS_TOKEN }} \
                         NETLIFY_WEBSITE=${{ secrets.NETLIFY_WEBSITE }}
